export interface Pet {
  id: string;
  name: string;
  breed: string;
  species: "dog" | "cat" | "other";
  age: { months: number; label: string };
  gender: "male" | "female";
  size: "small" | "medium" | "large";
  location: { city: string; state: string; lat: number; lng: number };
  images: string[];
  verified: boolean;
  vaccinated: boolean;
  spayed: boolean;
  temperament: string[];
  adoptionFee: number;
  ownerId: string;
  ownerName: string;
  ownerAvatar: string;
  ownerRating: number;
  ownerMemberSince: string;
  description: string;
  healthNotes: string;
  createdAt: string;
  distance?: string;
}

export const pets: Pet[] = [
  {
    id: "pet-001",
    name: "Bruno",
    breed: "Golden Retriever",
    species: "dog",
    age: { months: 24, label: "2 years" },
    gender: "male",
    size: "large",
    location: { city: "Mumbai", state: "Maharashtra", lat: 19.076, lng: 72.8777 },
    images: ["/images/pets/pet-001/1.jpg", "/images/pets/pet-001/2.jpg"],
    verified: true,
    vaccinated: true,
    spayed: true,
    temperament: ["friendly", "playful", "energetic"],
    adoptionFee: 0,
    ownerId: "owner-001",
    ownerName: "Rahul Sharma",
    ownerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=RahulSharma",
    ownerRating: 4.8,
    ownerMemberSince: "2024-03-15",
    description: "Bruno is a loving Golden Retriever who adores playing fetch and swimming. He's great with kids and other dogs. House-trained and knows basic commands.",
    healthNotes: "Up to date on all vaccinations. Recent vet check in May 2026. No health issues.",
    createdAt: "2026-06-01T10:00:00Z",
    distance: "3.2 km",
  },
  {
    id: "pet-002",
    name: "Milo",
    breed: "Beagle",
    species: "dog",
    age: { months: 8, label: "8 months" },
    gender: "male",
    size: "medium",
    location: { city: "Delhi", state: "Delhi", lat: 28.7041, lng: 77.1025 },
    images: ["/images/pets/pet-002/1.jpg", "/images/pets/pet-002/2.jpg"],
    verified: true,
    vaccinated: true,
    spayed: false,
    temperament: ["curious", "playful", "gentle"],
    adoptionFee: 500,
    ownerId: "owner-002",
    ownerName: "Priya Verma",
    ownerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=PriyaVerma",
    ownerRating: 4.9,
    ownerMemberSince: "2025-01-20",
    description: "Milo is an adorable Beagle puppy who loves to explore and sniff everything. Very food motivated — perfect for training!",
    healthNotes: "First round of vaccinations complete. Dewormed recently.",
    createdAt: "2026-06-10T14:30:00Z",
    distance: "5.8 km",
  },
  {
    id: "pet-003",
    name: "Luna",
    breed: "Persian Cat",
    species: "cat",
    age: { months: 18, label: "1.5 years" },
    gender: "female",
    size: "small",
    location: { city: "Bangalore", state: "Karnataka", lat: 12.9716, lng: 77.5946 },
    images: ["/images/pets/pet-003/1.jpg", "/images/pets/pet-003/2.jpg"],
    verified: true,
    vaccinated: true,
    spayed: true,
    temperament: ["calm", "affectionate", "independent"],
    adoptionFee: 1000,
    ownerId: "owner-003",
    ownerName: "Arjun Nair",
    ownerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ArjunNair",
    ownerRating: 4.7,
    ownerMemberSince: "2024-08-05",
    description: "Luna is a gorgeous Persian cat with a calm demeanor. She loves lounging in sunlight and getting head scratches. Perfect for apartment living.",
    healthNotes: "Fully vaccinated. Spayed. No allergies or health concerns.",
    createdAt: "2026-05-25T09:00:00Z",
    distance: "1.5 km",
  },
  {
    id: "pet-004",
    name: "Rocky",
    breed: "German Shepherd",
    species: "dog",
    age: { months: 36, label: "3 years" },
    gender: "male",
    size: "large",
    location: { city: "Pune", state: "Maharashtra", lat: 18.5204, lng: 73.8567 },
    images: ["/images/pets/pet-004/1.jpg", "/images/pets/pet-004/2.jpg"],
    verified: false,
    vaccinated: true,
    spayed: true,
    temperament: ["loyal", "protective", "intelligent"],
    adoptionFee: 0,
    ownerId: "owner-004",
    ownerName: "Deepak Joshi",
    ownerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=DeepakJoshi",
    ownerRating: 4.5,
    ownerMemberSince: "2025-06-10",
    description: "Rocky is a well-trained German Shepherd. He's protective yet gentle with family. Needs a home with a yard or regular outdoor access.",
    healthNotes: "All vaccinations up to date. Hip joint check - all clear.",
    createdAt: "2026-06-15T16:00:00Z",
    distance: "7.1 km",
  },
  {
    id: "pet-005",
    name: "Coco",
    breed: "Shih Tzu",
    species: "dog",
    age: { months: 12, label: "1 year" },
    gender: "female",
    size: "small",
    location: { city: "Hyderabad", state: "Telangana", lat: 17.385, lng: 78.4867 },
    images: ["/images/pets/pet-005/1.jpg", "/images/pets/pet-005/2.jpg"],
    verified: true,
    vaccinated: true,
    spayed: false,
    temperament: ["playful", "affectionate", "lap-dog"],
    adoptionFee: 2000,
    ownerId: "owner-005",
    ownerName: "Sneha Reddy",
    ownerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SnehaReddy",
    ownerRating: 5.0,
    ownerMemberSince: "2024-11-01",
    description: "Coco is a fluffy Shih Tzu who loves being the center of attention. She's great with children and adapts well to apartment living.",
    healthNotes: "Vaccinations complete. Regular grooming schedule maintained.",
    createdAt: "2026-06-20T11:30:00Z",
    distance: "2.3 km",
  },
  {
    id: "pet-006",
    name: "Simba",
    breed: "Indian Spitz",
    species: "dog",
    age: { months: 6, label: "6 months" },
    gender: "male",
    size: "medium",
    location: { city: "Jaipur", state: "Rajasthan", lat: 26.9124, lng: 75.7873 },
    images: ["/images/pets/pet-006/1.jpg", "/images/pets/pet-006/2.jpg"],
    verified: false,
    vaccinated: true,
    spayed: false,
    temperament: ["alert", "cheerful", "adaptable"],
    adoptionFee: 0,
    ownerId: "owner-006",
    ownerName: "Vikram Singh",
    ownerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=VikramSingh",
    ownerRating: 4.3,
    ownerMemberSince: "2026-01-15",
    description: "Simba is an Indian Spitz puppy — alert, cheerful, and easy to train. He's great for first-time pet owners.",
    healthNotes: "First vaccinations done. Needs follow-up shots in 2 months.",
    createdAt: "2026-06-22T08:00:00Z",
    distance: "12.0 km",
  },
  {
    id: "pet-007",
    name: "Whiskers",
    breed: "British Shorthair",
    species: "cat",
    age: { months: 30, label: "2.5 years" },
    gender: "male",
    size: "small",
    location: { city: "Chennai", state: "Tamil Nadu", lat: 13.0827, lng: 80.2707 },
    images: ["/images/pets/pet-007/1.jpg", "/images/pets/pet-007/2.jpg"],
    verified: true,
    vaccinated: true,
    spayed: true,
    temperament: ["independent", "curious", "calm"],
    adoptionFee: 500,
    ownerId: "owner-007",
    ownerName: "Kavitha Iyer",
    ownerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=KavithaIyer",
    ownerRating: 4.6,
    ownerMemberSince: "2025-04-20",
    description: "Whiskers is a gorgeous British Shorthair with plush grey fur and round copper eyes. He's calm, low-maintenance, litter-trained, and gets along well with other cats.",
    healthNotes: "Fully vaccinated and neutered. Healthy weight, no issues.",
    createdAt: "2026-06-05T12:00:00Z",
    distance: "4.6 km",
  },
  {
    id: "pet-008",
    name: "Bella",
    breed: "Labrador Retriever",
    species: "dog",
    age: { months: 4, label: "4 months" },
    gender: "female",
    size: "large",
    location: { city: "Kolkata", state: "West Bengal", lat: 22.5726, lng: 88.3639 },
    images: ["/images/pets/pet-008/1.jpg", "/images/pets/pet-008/2.jpg"],
    verified: true,
    vaccinated: false,
    spayed: false,
    temperament: ["friendly", "energetic", "trainable"],
    adoptionFee: 1500,
    ownerId: "owner-008",
    ownerName: "Sourav Das",
    ownerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SouravDas",
    ownerRating: 4.4,
    ownerMemberSince: "2025-09-10",
    description: "Bella is a Labrador puppy full of energy and love. She's learning basic commands and is incredibly food-motivated.",
    healthNotes: "Partial vaccinations. Needs second round in 3 weeks.",
    createdAt: "2026-06-18T15:00:00Z",
    distance: "6.4 km",
  },
  {
    id: "pet-009",
    name: "Oreo",
    breed: "Indian Pariah Dog",
    species: "dog",
    age: { months: 14, label: "1 year 2 months" },
    gender: "male",
    size: "medium",
    location: { city: "Chandigarh", state: "Punjab", lat: 30.7333, lng: 76.7794 },
    images: ["/images/pets/pet-009/1.jpg", "/images/pets/pet-009/2.jpg"],
    verified: true,
    vaccinated: true,
    spayed: true,
    temperament: ["intelligent", "loyal", "adaptable"],
    adoptionFee: 0,
    ownerId: "owner-009",
    ownerName: "Manpreet Kaur",
    ownerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ManpreetKaur",
    ownerRating: 4.9,
    ownerMemberSince: "2024-06-01",
    description: "Oreo is a handsome Indian Pariah Dog — one of the healthiest and most intelligent native breeds. He's incredibly loyal, easy to train, and thrives in Indian weather. Perfect for families looking for a low-maintenance, loving companion.",
    healthNotes: "Fully vaccinated. Excellent health — Indian Pariahs are naturally resilient with strong immunity.",
    createdAt: "2026-06-12T07:00:00Z",
    distance: "9.2 km",
  },
  {
    id: "pet-010",
    name: "Ginger",
    breed: "Pug",
    species: "dog",
    age: { months: 20, label: "1 year 8 months" },
    gender: "female",
    size: "small",
    location: { city: "Ahmedabad", state: "Gujarat", lat: 23.0225, lng: 72.5714 },
    images: ["/images/pets/pet-010/1.jpg", "/images/pets/pet-010/2.jpg"],
    verified: true,
    vaccinated: true,
    spayed: true,
    temperament: ["playful", "charming", "loving"],
    adoptionFee: 1000,
    ownerId: "owner-010",
    ownerName: "Neha Patel",
    ownerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=NehaPatel",
    ownerRating: 4.8,
    ownerMemberSince: "2025-02-14",
    description: "Ginger is an adorable Pug with a wrinkly face and big soulful eyes. She loves cuddling on the couch and following her humans everywhere. Perfect apartment companion!",
    healthNotes: "All vaccinations current. Regular vet check-ups. Eyes and breathing monitored.",
    createdAt: "2026-06-08T13:00:00Z",
    distance: "0.8 km",
  },
  {
    id: "pet-011",
    name: "Shadow",
    breed: "Indie (Mixed)",
    species: "dog",
    age: { months: 10, label: "10 months" },
    gender: "male",
    size: "medium",
    location: { city: "Lucknow", state: "Uttar Pradesh", lat: 26.8467, lng: 80.9462 },
    images: ["/images/pets/pet-011/1.jpg", "/images/pets/pet-011/2.jpg"],
    verified: false,
    vaccinated: true,
    spayed: false,
    temperament: ["resilient", "loving", "adaptable"],
    adoptionFee: 0,
    ownerId: "owner-011",
    ownerName: "Adopt Lucknow Shelter",
    ownerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=AdoptLucknowShelter",
    ownerRating: 4.2,
    ownerMemberSince: "2023-12-01",
    description: "Shadow is a handsome indie pup rescued from the streets. He's incredibly grateful for any affection and adapts quickly to new environments.",
    healthNotes: "Vaccinated and dewormed at shelter. Healthy and active.",
    createdAt: "2026-06-25T10:00:00Z",
    distance: "1.2 km",
  },
  {
    id: "pet-012",
    name: "Mittens",
    breed: "Indian Domestic Cat",
    species: "cat",
    age: { months: 9, label: "9 months" },
    gender: "female",
    size: "medium",
    location: { city: "Goa", state: "Goa", lat: 15.2993, lng: 74.124 },
    images: ["/images/pets/pet-012/1.jpg", "/images/pets/pet-012/2.jpg"],
    verified: true,
    vaccinated: true,
    spayed: false,
    temperament: ["docile", "affectionate", "gentle"],
    adoptionFee: 2500,
    ownerId: "owner-012",
    ownerName: "Fernandes Family",
    ownerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=FernandesFamily",
    ownerRating: 5.0,
    ownerMemberSince: "2025-07-20",
    description: "Mittens is a beautiful Indian Domestic Cat with classic tabby markings. She follows you around the house, loves belly rubs, and is perfectly adapted to Indian homes.",
    healthNotes: "First vaccinations done. Spaying scheduled for next month.",
    createdAt: "2026-06-28T09:30:00Z",
    distance: "15.3 km",
  },
];
